"use client";
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "rsuite/dist/rsuite.min.css";
import "./globals.css";
import { Provider, useSelector } from "react-redux";
import store from "@/store";
import { GlobalState } from "@/types/storeTypes";
import { ThemeProvider } from "@/components/Pars/ThemeContext";

// const inter = Inter({ subsets: ['latin'] });
const montserrat = Montserrat({
   weight: ["400", "500", "600", "700", "800", "900"],
   subsets: ["latin"],
   variable: "--font-montserrat",
});

// export const metadata: Metadata = {
//    title: "Create Next App",
//    description: "Generated by create next app",
// };

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body className={`${montserrat.variable}`}>
            <ThemeProvider>
               <Provider store={store}>{children} </Provider>
            </ThemeProvider>
         </body>
      </html>
   );
}
